- name: update and upgrade apt-get 
  import_tasks: update.yml
  when: (action == "install") or (action == "update")

- name: install required packages 
  import_tasks: install.yml
  when: (action == "install")